let articlesArray = [
    {
        id: 1,
        preview: 'images/article-preview-1.png',
        tag: 'book',
        name: 'Don’t Underestimate The Software Administration UX',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
    {
        id: 2,
        preview: 'images/article-preview-1.png',
        tag: 'education build',
        name: 'How To Improve Product Roadmaps',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
    {
        id: 3,
        preview: 'images/article-preview-1.png',
        tag: 'apps',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
    {
        id: 4,
        preview: 'images/article-preview-2.png',
        tag: 'charity',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-2.png',
        articleImg2: 'images/article-img-1.png',
    },
    {
        id: 5,
        preview: 'images/article-preview-1.png',
        tag: 'apps',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
    {
        id: 6,
        preview: 'images/article-preview-2.png',
        tag: 'data',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
    {
        id: 7,
        preview: 'images/article-preview-1.png',
        tag: 'charity',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
    {
        id: 8,
        preview: 'images/article-preview-1.png',
        tag: 'book',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-2.png',
        articleImg2: 'images/article-img-1.png',
    },
    {
        id: 9,
        preview: 'images/article-preview-1.png',
        tag: 'landing',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
    {
        id: 10,
        preview: 'images/article-preview-2.png',
        tag: 'website',
        name: 'Don’t Underestimate The Software Administration UX',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
    {
        id: 11,
        preview: 'images/article-preview-2.png',
        tag: 'education build',
        name: 'How To Improve Product Roadmaps',
        articleImg1: 'images/article-img-2.png',
        articleImg2: 'images/article-img-1.png',
    },
    {
        id: 12,
        preview: 'images/article-preview-2.png',
        tag: 'apps',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
    {
        id: 13,
        preview: 'images/article-preview-2.png',
        tag: 'landing',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-2.png',
        articleImg2: 'images/article-img-1.png',
    },
    {
        id: 14,
        preview: 'images/article-preview-1.png',
        tag: 'website',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-2.png',
        articleImg2: 'images/article-img-1.png',
    },
    {
        id: 15,
        preview: 'images/article-preview-2.png',
        tag: 'data',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-2.png',
        articleImg2: 'images/article-img-1.png',
    },
    {
        id: 16,
        preview: 'images/article-preview-2.png',
        tag: 'design',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-2.png',
        articleImg2: 'images/article-img-1.png',
    },
    {
        id: 17,
        preview: 'images/article-preview-2.png',
        tag: 'book',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-2.png',
        articleImg2: 'images/article-img-1.png',
    },
    {
        id: 18,
        preview: 'images/article-preview-2.png',
        tag: 'apps',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-2.png',
        articleImg2: 'images/article-img-1.png',
    },
    {
        id: 19,
        preview: 'images/article-preview-3.png',
        tag: 'book',
        name: 'Don’t Underestimate The Software Administration UX',
        articleImg1: 'images/article-img-2.png',
        articleImg2: 'images/article-img-1.png',
    },
    {
        id: 20,
        preview: 'images/article-preview-3.png',
        tag: 'education build',
        name: 'How To Improve Product Roadmaps',
        articleImg1: 'images/article-img-2.png',
        articleImg2: 'images/article-img-1.png',
    },
    {
        id: 21,
        preview: 'images/article-preview-3.png',
        tag: 'landing',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-2.png',
        articleImg2: 'images/article-img-1.png',
    },
    {
        id: 22,
        preview: 'images/article-preview-2.png',
        tag: 'design',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-2.png',
        articleImg2: 'images/article-img-1.png',
    },
    {
        id: 23,
        preview: 'images/article-preview-1.png',
        tag: 'charity',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
    {
        id: 24,
        preview: 'images/article-preview-2.png',
        tag: 'landing',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
    {
        id: 25,
        preview: 'images/article-preview-3.png',
        tag: 'charity',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
    {
        id: 26,
        preview: 'images/article-preview-3.png',
        tag: 'book',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
    {
        id: 27,
        preview: 'images/article-preview-3.png',
        tag: 'design',
        name: 'Definitive Guide to Make a Daily More Productive Working Flow. ',
        articleImg1: 'images/article-img-1.png',
        articleImg2: 'images/article-img-2.png',
    },
]

export default articlesArray
